name: 'Android Kernel Builder Action'
author: 'Ragebreaker'
description: "Action to build Android kernel"

inputs:
  KERNEL_CLONE_CMD:
    description: 'Command to clone kernel source code'
    required: true
  KERNEL_CONFIG:
    description: 'Kernel configuration name (e.g. defconfig)'
    required: true
  ARCH:
    description: 'Target architecture'
    required: true
    default: 'arm64'
  MAKE_ARGS:
    description: 'Arguments for make command (both defconfig and kernel)'
    required: false
    default: false
    
  # Toolchain options
  COMPILER:
    description: 'compiler to use (gcc|clang)'
    required: false
    default: 'gcc'
  TOOLCHAIN_CLONE_CMD:
    description: 'Link of compiler to clone and use'
    required: false
    default: 'git clone https://github.com/djb77/aarch64-linux-android-4.9 ./toolchain/gcc'
    
  # Features
  ENABLE_KSU:
    description: 'Enable KernelSU support for non-gki (non-kprobe) ( ONLY ENABLE IF NOT ALREADY INTEGRATED!!! )'
    required: false
    default: false
  KSU_CURL_COMMAND:
    description: 'External KernelSU curl command (check KernelSU readme)'
    required: false
    default: 'curl -LSs "https://raw.githubusercontent.com/mlm-games/KernelSU-Non-GKI/main/kernel/setup-subm.sh" | bash -s '
    
  ENABLE_CCACHE:
    description: 'Enable ccache support'
    required: false 
    default: true
    
  # Output options
  OUTPUT_PACKAGE_FORMAT:
    description: 'Output package format (anykernel3|boot.img)'
    required: false
    default: 'anykernel3'
  ANYKERNEL_URL:
    description: 'Url for anykernel3 repo.'
    required: false
    default: 'https://github.com/mlm-games/AnyKernel3'
    

runs:
  using: 'composite'
  steps:
    - name: Setup Build Environment
      shell: bash
      run: |
        sudo apt-get update
        set +e
        sudo apt-get install -y build-essential bc bison flex libssl-dev ccache binutils git make openssl curl zip kmod cpio libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-cer
        set -e
        
    - name: Setup ccache
      if: inputs.ENABLE_CCACHE == 'true'
      uses: hendrikmuhs/ccache-action@v1.2
        
    - name: Clone Kernel Source
      shell: bash
      run: |
        ${{ inputs.KERNEL_CLONE_CMD }} --depth=1 kernel_source
        
    - name: Setup Toolchain
      shell: bash
      run: |
        if [ "${{ inputs.COMPILER }}" = "clang" ]; then
          echo "Cloning clang repo..."
          ${{ inputs.TOOLCHAIN_CLONE_CMD }}
        else
          echo "Cloning GCC..."
          ${{ inputs.TOOLCHAIN_CLONE_CMD }}
        
    - name: Setup KernelSU
      if: inputs.ENABLE_KSU == 'true'
      shell: bash
      run: |
        ${{ inputs.KSU_CURL_COMMAND }}
        
    - name: Build Kernel
      shell: bash
      run: |
        cd kernel_source
        make ${{ inputs.KERNEL_CONFIG }} ARCH=${{ inputs.ARCH }} {{ inputs.MAKE_ARGS }}
        make -j$(nproc) ARCH=${{ inputs.ARCH }} {{ inputs.MAKE_ARGS }}
        
    - name: Package Kernel
      shell: bash
      run: |
        if [ "${{ inputs.OUTPUT_PACKAGE_FORMAT }}" = "anykernel3" ]; then
          git clone ${{ inputs.ANYKERNEL_URL }} --depth=1 AnyKernel3
          
          # Copy kernel
          cp arch/${{ inputs.ARCH }}/boot/Image* AnyKernel3/
          [ -f arch/${{ inputs.ARCH }}/boot/dtbo.img ] && \
            cp arch/${{ inputs.ARCH }}/boot/dtbo.img AnyKernel3/
          [ -f arch/${{ inputs.ARCH }}/boot/dtb.img ] && \
            cp arch/${{ inputs.ARCH }}/boot/dtb.img AnyKernel3/
            
          cd AnyKernel3
          zip -r9 ../../build/kernel-${{ github.sha }}.zip *

branding:
  icon: 'cpu' 
  color: 'blue'
